version: '3'

services:
  nginx:
    build: ./nginx
    ports:
      - 3000:80
    volumes:
      - ./app:/srv/www
      # - ./app:/srv/www:ro
      # - ./app:/srv/www:cached
      # - ./app:/srv/www:delegated
  
  php:
    build: ./php
    volumes:
      - ./app:/srv/www
